config:
  replacements:
    - registry: quay.io
      repo_mappings:
        rhoai/odh-operator-bundle: rhoai/odh-operator-bundle
        rhoai/odh-rhel8-operator: rhoai/odh-rhel8-operator
        rhoai/odh-ml-pipelines-launcher-rhel8: rhoai/odh-ml-pipelines-launcher-rhel8
        rhoai/odh-ml-pipelines-driver-rhel8: rhoai/odh-ml-pipelines-driver-rhel8
        rhoai/odh-kuberay-operator-controller-rhel8: rhoai/odh-kuberay-operator-controller-rhel8
        rhoai/odh-kueue-controller-rhel8: rhoai/odh-kueue-controller-rhel8
        rhoai/odh-kf-notebook-controller-rhel8: rhoai/odh-kf-notebook-controller-rhel8
        rhoai/odh-data-science-pipelines-operator-controller-rhel8: rhoai/odh-data-science-pipelines-operator-controller-rhel8
        rhoai/odh-mm-rest-proxy-rhel8: rhoai/odh-mm-rest-proxy-rhel8
        rhoai/odh-model-controller-rhel8: rhoai/odh-model-controller-rhel8
        rhoai/odh-modelmesh-serving-controller-rhel8: rhoai/odh-modelmesh-serving-controller-rhel8
        rhoai/odh-codeflare-operator-rhel8: rhoai/odh-codeflare-operator-rhel8
        rhoai/odh-trustyai-service-operator-rhel8: rhoai/odh-trustyai-service-operator-rhel8
        rhoai/odh-training-operator-rhel8: rhoai/odh-training-operator-rhel8
        rhoai/odh-dashboard-rhel8: rhoai/odh-dashboard-rhel8
        rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel8: rhoai/odh-data-science-pipelines-argo-workflowcontroller-rhel8
        rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8: rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8
        rhoai/odh-data-science-pipelines-argo-argoexec-rhel8: rhoai/odh-data-science-pipelines-argo-argoexec-rhel8
        rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8: rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8
        rhoai/odh-modelmesh-runtime-adapter-rhel8: rhoai/odh-modelmesh-runtime-adapter-rhel8
        rhoai/odh-notebook-controller-rhel8: rhoai/odh-notebook-controller-rhel8
        rhoai/odh-mlmd-grpc-server-rhel8: rhoai/odh-mlmd-grpc-server-rhel8
        rhoai/odh-ml-pipelines-api-server-v2-rhel8: rhoai/odh-ml-pipelines-api-server-v2-rhel8
        rhoai/odh-modelmesh-rhel8: rhoai/odh-modelmesh-rhel8
        rhoai/odh-trustyai-service-rhel8: rhoai/odh-trustyai-service-rhel8
        rhoai/odh-model-registry-operator-rhel8: rhoai/odh-model-registry-operator-rhel8
        rhoai/odh-model-registry-rhel8: rhoai/odh-model-registry-rhel8
  supported-ocp-versions:
    build:
      - name: v4.12
        base-image: registry.redhat.io/openshift4/ose-operator-registry:v4.12
      - name: v4.13
        base-image: registry.redhat.io/openshift4/ose-operator-registry:v4.13
      - name: v4.14
        base-image: registry.redhat.io/openshift4/ose-operator-registry:v4.14
      - name: v4.15
        base-image: registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.15
      - name: v4.16
        base-image: registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.16
      - name: v4.17
        base-image: registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.17
    release:
      - v4.12
      - v4.13
      - v4.14
      - v4.15
      - v4.16
      - v4.17
