#!productVersion=2.16.1
#!scmRevision=rhoai-2.16


product:
  name: Red Hat OpenShift Data Science
  abbreviation: rhods
  stage:  beta
  issueTrackerUrl: https://issues.redhat.com/projects/RHODS/issues
version: {{productVersion}}
milestone: beta
group: data-hub-{{productVersion}}

defaultBuildParameters:
  buildType: MVN
  environmentName: OpenJDK 17.0; RHEL 8; Mvn 3.9.1; Nodejs 18; npm 8
  buildCategory: SERVICE
  brewPullActive: true


builds:

  - name: trustyai-service-{{productVersion}}
    project: managed-open-data-hub
    scmUrl: https://github.com/red-hat-data-services/trustyai-explainability
    scmRevision: {{scmRevision}}
    alignmentParameters:
      - "-DdependencyOverride.io.grpc:grpc-bom@*=" #temp as the grpc bom package in pnc is not updated
    buildScript:  |

      VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo "VERSION environment variable set to: ${VERSION}"

      mvn -B clean package --file pom.xml -P service-minimal -DskipTests -Dquarkus.profile=rhoai
      zip -r trustyai-artifacts.zip explainability-service/target/
      mvn deploy:deploy-file  -Durl=${AProxDeployUrl} -DrepositoryId=indy-mvn -Dfile=trustyai-artifacts.zip -Dpackaging=zip -DgroupId=org.kie.trustyai -DartifactId=explainability-service -Dversion=${VERSION}


outputPrefixes:
  releaseFile: rhods
  releaseDir: rhods


flow:
  licensesGeneration:
    strategy: IGNORE
  repositoryGeneration:
    strategy: IGNORE
  javadocGeneration:
    strategy: IGNORE
  sourcesGeneration:
    strategy: IGNORE
